name: Community Blocklist Aggregator

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run smart aggregator script
        run: python smart_aggregator.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git pull --rebase
          
          # Add the entire 'community' directory to the commit
          git add community/
          
          if git diff --staged --quiet; then
            echo "No file changes to commit."
          else
            # Use the commit message from inside the 'community' directory
            git commit -F community/commit_message.txt
            git push
          fi
