name: Build Community Blocklist (DEBUG)

on:
  workflow_dispatch:

jobs:
  build-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: 3. Install dependencies
        run: pip install requests

      - name: 4. Run smart aggregator script
        continue-on-error: true
        id: script_step
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python smart_aggregator.py

      - name: 5. List all files in the directory
        run: |
          echo "--- Listing all files in workspace ---"
          ls -R
          echo "------------------------------------"

      - name: 6. Check if the script failed
        if: steps.script_step.outcome == 'failure'
        run: |
          echo "::error::Python script failed. Please check the logs in Step 4."
          exit 1