name: Build Community Blocklist

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run smart aggregator script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python smart_aggregator.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          
          if git diff --staged --quiet; then
            echo "No file changes to commit."
          else
            git commit -m "Update community blocklist and state"
            git push
          fi